package shareddto;

public enum EventType {
    LOGIN_EMPLOYEE,
    LOGOUT_EMPLOYEE,
    CREATE_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    GET_EMPLOYEE,
    GET_BRANCH_INFO,
    GET_INVERTORY_ITEMS,
    UPDATE_INVENTORY_ITEM,
    BUY_INVENTORY_ITEM,
    LIST_BRANCH_EMPLOYEES
}
